#ifndef DIO_PRV_H
#define DIO_PRV_H

	#define 	INPUT 									0
	#define 	OUTPUT 									1

	#define 	LOW 									0
	#define 	HIGH 									1

	#define 	FLOATING 								0
	#define 	PULLEDUP 								1

	#define 	CONC(B7,B6,B5,B4,B3,B2,B1,B0)			CONC_HELPER(B7,B6,B5,B4,B3,B2,B1,B0)
	#define		CONC_HELPER(B7,B6,B5,B4,B3,B2,B1,B0)	0b##B7##B6##B5##B4##B3##B2##B1##B0

	#define 	PORTA_DIRECTION							CONC(PORTAPIN0,PORTAPIN1,PORTAPIN2,PORTAPIN3,PORTAPIN4,PORTAPIN5,PORTAPIN6,PORTAPIN7)
	#define 	PORTB_DIRECTION							CONC(PORTBPIN0,PORTBPIN1,PORTBPIN2,PORTBPIN3,PORTBPIN4,PORTBPIN5,PORTBPIN6,PORTBPIN7)
	#define 	PORTC_DIRECTION							CONC(PORTCPIN0,PORTCPIN1,PORTCPIN2,PORTCPIN3,PORTCPIN4,PORTCPIN5,PORTCPIN6,PORTCPIN7)
	#define 	PORTD_DIRECTION							CONC(PORTDPIN0,PORTDPIN1,PORTDPIN2,PORTDPIN3,PORTDPIN4,PORTDPIN5,PORTDPIN6,PORTDPIN7)

	#define 	PORTA_VALUE								CONC(VALPORTAPIN0,VALPORTAPIN1,VALPORTAPIN2,VALPORTAPIN3,VALPORTAPIN4,VALPORTAPIN5,VALPORTAPIN6,VALPORTAPIN7)
	#define 	PORTB_VALUE								CONC(VALPORTBPIN0,VALPORTBPIN1,VALPORTBPIN2,VALPORTBPIN3,VALPORTBPIN4,VALPORTBPIN5,VALPORTBPIN6,VALPORTBPIN7)
	#define 	PORTC_VALUE								CONC(VALPORTCPIN0,VALPORTCPIN1,VALPORTCPIN2,VALPORTCPIN3,VALPORTCPIN4,VALPORTCPIN5,VALPORTCPIN6,VALPORTCPIN7)
	#define 	PORTD_VALUE								CONC(VALPORTDPIN0,VALPORTDPIN1,VALPORTDPIN2,VALPORTDPIN3,VALPORTDPIN4,VALPORTDPIN5,VALPORTDPIN6,VALPORTDPIN7)


#endif
